### PR TITLE
DRTII-1110 fixing internal server error and also message for invalidF…

### PR DESCRIPTION
**Pull request by ngu04**
- adding username check while password reset
- adding relevant message for invalidFederatedIdentityActionMessage error

### CODE REVIEW

**Comment by sureshnature** [comment]
The email address you have sent to ***@***.*** is for a legacy domain and will shortly be removed.

Please update your address book and send to the same address but having removed .gsi. from the domain part.

Mail to the legacy addresses will stop working in a few weeks.

**Comment by franklini** [comment]
The email address you have sent to ***@***.*** is for a legacy domain and will shortly be removed.

Please update your address book and send to the same address but having removed .gsi. from the domain part.

Mail to the legacy addresses will stop working in a few weeks.

**Comment by ngu04** [comment]
> The email address you have sent to ***@***.*** is for a legacy domain and will shortly be removed. Please update your address book and send to the same address but having removed .gsi. from the domain part. Mail to the legacy addresses will stop working in a few weeks.

**Comment by ngu04** [comment]
There is no gsi in domain part

**Review by jremes-ho — APPROVED** [review]
LGTM.

**Pull request merged**
