### PR TITLE
Move title into a 'proposition'

### PR DESCRIPTION
**Pull request by daniel-ac-martin**
Moves the title of the page into a 'proposition' which is
the GovUK-idiomatic way to display it.

Also fixes a link.

Original:
kc-govuk-master-2017-05-10

Proposed:
kc-govuk-title-in-proposition

The alignment is weird to my eyes but this is how they do it on GovUK!

### CODE REVIEW

**Comment by paulwaitehomeoffice** [comment]
I’m with you in general on the `with-proposition` thing.

I’d removed that because, on our project, we have our service name in place of GOV.UK, rather than as a proposition. This might be because we’re an internal service — I’ll ask our designer.

**Comment by paulwaitehomeoffice** [comment]
On the link, that was slightly more intentional — I’d assumed that different theme users might want to link back to different home pages. As ours is an internal project, linking to http://gov.uk/ doesn’t make a great deal of sense, although I understand if it’s how the GOV.UK Template should be used.

Keycloak themes aren’t very customisable, so it’s tricky, but we do have two fields to work with — “Display Name”, and “Display Name HTML”. I was thinking that, although it’s a bit shonky, we could use the former for the service name, and the latter for the home page link.

**Comment by daniel-ac-martin** [comment]
In my version 'Keycloak' (the 'display name') links through to / which should work for most of our services.

In GovUK-land the link on the left should always go to http://gov.uk I believe.

I don't think 'Display Name HTML' is helpful for links. The current version seems to produce the following HTML:
```html
<a href="<div class=&quot;kc-logo-text&quot;><span>Keycloak</span></div>" title="Go to the Keycloak homepage" id="logo" class="content">
              <img src="/auth/resources/3.0.0.final/login/govuk_latest/vendor/govuk_template/images/gov.uk_logotype_crown_invert_trans.png?0.19.2" alt="" width="36" height="32"> Keycloak
            </a>
```
i.e. The href is nonsense.

**Comment by daniel-ac-martin** [comment]
In terms of customisations to GovUK styling. I think we should have a standard GovUK theme and then separate themes for customisations if they are required.

LEV also uses a variation of GovUK as it is also an internal service but I am content for login pages to use standard GovUK.

**Comment by paulwaitehomeoffice** [comment]
Yeah, the idea was that “Display Name HTML” would only be used for the home page link href in the theme, so users would customise it in Keycloak’s admin console to contain a URL, instead of an HTML version of the service name.

The admin console itself can be themed too, so I did think about adding a GOV.UK theme for that which just re-labelled the Display Name HTML field.

This is probably over-complicating it, but it would be good to know whether `/` is likely to be a reliable link to individual service’s actual home pages, or (although it sounds iffy) whether we should possibly avoid any links back to the actual service altogether.

**Comment by daniel-ac-martin** [comment]
Ah I see now.

I think that using the 'Display Name HTML' for the link is a bad idea as it's really changing what the field was originally intended for.

I also think I was wrong about '/' being suitable. Instead I think we should simple not link back to the service as I don't think there's a nice way to do it. (As realms can be used for logging in to multiple things.)

Potentially, we could link to the 'redirect_uri' which is a parameter in the query string. But I'm not sure whether that is accessible. It also wouldn't be of too much use as it would just redirect you back to the current page.

I'll push up a commit to link to the current page. i.e. '#'.

**Comment by paulwaitehomeoffice** [comment]
I take your point about the “Display Name HTML” field.

As far as I know, that field is only used within the theme, so changing how it’s used within the theme (and therefore what its contents are) is theoretically in scope. But I agree it’s weird thing to do — anyone familiar with Keycloak would, I think, be surprised.

Is it possible that we’re better off not having the logo area be a link at all, rather than linking to the current page?

**Comment by paulwaitehomeoffice** [comment]
On the GOV.UK/proposition title issue, our service is adapting the GOV.UK Template to follow the Home Office beta header pattern for internal services:

https://home-office-digital-patterns.herokuapp.com/header

I agree that the default GOV.UK Keycloak theme should probably follow GOV.UK, and that I should create a separate version for adaptations of it. (At some point, hopefully GOV.UK will incorporate these variations.)

**Comment by daniel-ac-martin** [comment]
I think keeping it as a link to the current page would give more guarantees in terms of consistency with GovUK. I don't think it does any harm even if it isn't especially useful.

BTW who did the https://home-office-digital-patterns.herokuapp.com site?

**Comment by paulwaitehomeoffice** [comment]
> who did the https://home-office-digital-patterns.herokuapp.com site

Not a clue, but I can put you in touch with our interaction designer, who knows a bit more about the cross-government design standards stuff. I understand that it’s in beta, and has been for some time, but may be the way things are going.

Of course, it may also be Home Office-specific, which the GOV.UK stuff obviously isn’t.

**Comment by paulwaitehomeoffice** [comment]
I have one other idea for allowing theme users to include a link to their service’s home page: add the entire HTML for the home page link in the Display Name HTML field:

htmldisplayname

I’ve searched the 3.0 Keycloak theme, and this wouldn’t conflict with any existing use of  `displayNameHtml`.

It’s a bit fiddly, and it does mean there’s a chance of errors, but I think being able to link to the service home page from the sign in screen could be quite important for some services.

**Comment by daniel-ac-martin** [comment]
I think that's probably a good idea.
I don't suppose you're familiar with the syntax on how to implement it? (I'd guess we need to fail back to markup currently in the PR if the variable isn't set?)

**Comment by daniel-ac-martin** [comment]
The only issue is that it probably needs the `id` attribute to be set on it. So there's a good chance people will mess it up. But I suppose we can accept that risk.

**Comment by paulwaitehomeoffice** [comment]
Yeah definite scope for breaking it, but given Keycloak’s limitations I think it’s the best we can do.

Right yes, so it seems like Keycloak will give you the displayName value in place of displayNameHtml, if displayNameHtml isn’t set. Which isn’t very useful for our purposes. I think the Freemarker syntax we want is this:

```
<#if realm.displayNameHtml?? || realm.displayName??>
  <div class="header-proposition">
    <div class="content"><#if realm.displayNameHtml?? && realm.displayNameHtml != realm.displayName>
      ${realm.displayNameHtml}<#elseif realm.displayName??>
      <a href="/" id="proposition-name">${realm.displayName}</a></#if>
    </div>
  </div></#if>
```

**Comment by daniel-ac-martin** [comment]
@paulwaitehomeoffice: That looks like it works. :-)

**Comment by paulwaitehomeoffice** [comment]
Marvellous, thanks for popping that in.

**Pull request merged**
