### PR TITLE
Task/add terms page

### PR DESCRIPTION
**Pull request by aarongill1**
Added page for LEV service Terms and Conditions. Due to this requiring a login theme, duplicate code from parent theme required.  Also added some information in the footer. This wording has been reviewed by HMPO policy representatives and LEV service manager. 

Screenshots of page included.

screenshot

### CODE REVIEW

**Comment by daniel-ac-martin** [comment]
Very lazy with the screenshots there @aarongill1! ;-P
You could have spliced them together nicely in `gimp`.

**Comment by aarongill1** [comment]
> Very lazy with the screenshots there @aarongill1! ;-P
> You could have spliced them together nicely in `gimp`.

Updated in a desperate need for validation @daniel-ac-martin

**Comment by daniel-ac-martin** [comment]
@aarongill1: Much nicer!

**Comment by daniel-ac-martin** [comment]
It looks like the apostrophes are not appearing.

**Comment by aarongill1** [comment]
> It looks like the apostrophes are not appearing.

Fixed

**Comment by Amir-Tayabali** [comment]
I've tested this out and it looks like it's working perfectly.
Thank you great job

**Pull request merged**
